using RequestDesk.Domain.Common;
using RequestDesk.Domain.Customers;
using RequestDesk.Domain.Users;

namespace RequestDesk.Domain.Requests;

/// <summary>
/// The aggregate root. Every change to a request goes through a method on this class, which is
/// where the state machine and the role rules are enforced. Controllers and handlers never set
/// state directly.
/// </summary>
public sealed class ServiceRequest : Entity
{
    private readonly List<RequestComment> _comments = [];
    private readonly List<RequestAttachment> _attachments = [];
    private readonly List<RequestStatusHistory> _history = [];

    private ServiceRequest()
    {
    }

    /// <summary>Human-readable id such as <c>RD-000042</c>. Generated by the database on insert.</summary>
    public string ReferenceNumber { get; private set; } = null!;

    public string Title { get; private set; } = null!;

    public string Description { get; private set; } = null!;

    public RequestPriority Priority { get; private set; }

    public RequestStatus Status { get; private set; }

    public Guid CustomerId { get; private set; }

    public Customer? Customer { get; private set; }

    public Guid? AssignedAgentId { get; private set; }

    public AppUser? AssignedAgent { get; private set; }

    public Guid CreatedById { get; private set; }

    public DateTimeOffset CreatedAt { get; private set; }

    public DateTimeOffset UpdatedAt { get; private set; }

    public IReadOnlyCollection<RequestComment> Comments => _comments;

    public IReadOnlyCollection<RequestAttachment> Attachments => _attachments;

    public IReadOnlyCollection<RequestStatusHistory> History => _history;

    public bool IsOpen => RequestStatusMachine.IsOpen(Status);

    public static ServiceRequest Create(
        Guid customerId,
        string title,
        string description,
        RequestPriority priority,
        Actor actor,
        DateTimeOffset now)
    {
        if (actor.IsCustomer && actor.CustomerId != customerId)
        {
            throw new PermissionDeniedException("A customer may only open requests on their own account.");
        }

        title = (title ?? string.Empty).Trim();
        description = (description ?? string.Empty).Trim();

        if (title.Length == 0)
        {
            throw new DomainRuleException("A title is required.");
        }

        if (title.Length > RequestLimits.MaxTitleLength)
        {
            throw new DomainRuleException($"A title may be at most {RequestLimits.MaxTitleLength} characters.");
        }

        if (description.Length == 0)
        {
            throw new DomainRuleException("A description is required.");
        }

        if (description.Length > RequestLimits.MaxDescriptionLength)
        {
            throw new DomainRuleException($"A description may be at most {RequestLimits.MaxDescriptionLength} characters.");
        }

        if (!Enum.IsDefined(priority))
        {
            throw new DomainRuleException("Unknown priority.");
        }

        var request = new ServiceRequest
        {
            Title = title,
            Description = description,
            Priority = priority,
            Status = RequestStatus.New,
            CustomerId = customerId,
            CreatedById = actor.UserId,
            CreatedAt = now,
            UpdatedAt = now,
        };

        request._history.Add(RequestStatusHistory.Record(request.Id, null, RequestStatus.New, actor.UserId, "Request created", now));
        return request;
    }

    /// <summary>
    /// Move the request to a new status. Checks legality first (an illegal move is a 409 with the
    /// legal set, whoever asked) and then permission (a legal move this actor may not make is a 403).
    /// Every successful call appends exactly one history row.
    /// </summary>
    public RequestStatusHistory ChangeStatus(RequestStatus to, Actor actor, string? reason, DateTimeOffset now)
    {
        EnsureCanView(actor);

        if (!RequestStatusMachine.CanTransition(Status, to))
        {
            throw new IllegalTransitionException(Status, to, RequestStatusMachine.LegalTargets(Status));
        }

        if (!RequestPolicy.CanTransition(this, actor, to))
        {
            throw new PermissionDeniedException($"A {actor.Role} may not move a request from {Status} to {to}.");
        }

        if (reason is { Length: > RequestLimits.MaxReasonLength })
        {
            throw new DomainRuleException($"A reason may be at most {RequestLimits.MaxReasonLength} characters.");
        }

        var entry = RequestStatusHistory.Record(Id, Status, to, actor.UserId, reason, now);
        _history.Add(entry);
        Status = to;
        UpdatedAt = now;
        return entry;
    }

    /// <summary>Set or clear the assigned agent. The caller has already checked the target user is staff.</summary>
    public void Assign(Guid? agentId, Actor actor, DateTimeOffset now)
    {
        EnsureCanView(actor);

        if (!RequestPolicy.CanAssign(this, actor, agentId))
        {
            throw new PermissionDeniedException(
                IsOpen
                    ? $"A {actor.Role} may not change the assignment of this request."
                    : "A closed or cancelled request cannot be reassigned.");
        }

        if (AssignedAgentId == agentId)
        {
            return;
        }

        AssignedAgentId = agentId;
        AssignedAgent = null;
        UpdatedAt = now;
    }

    public RequestComment AddComment(string body, Actor actor, DateTimeOffset now)
    {
        EnsureCanView(actor);

        if (!RequestPolicy.CanComment(this, actor))
        {
            throw new PermissionDeniedException("You may not comment on this request.");
        }

        var comment = RequestComment.Create(Id, body, actor.UserId, now);
        _comments.Add(comment);
        UpdatedAt = now;
        return comment;
    }

    public RequestAttachment AddAttachment(
        string fileName,
        string contentType,
        long sizeBytes,
        string storageKey,
        Actor actor,
        DateTimeOffset now)
    {
        EnsureCanView(actor);

        if (!RequestPolicy.CanAttach(this, actor))
        {
            throw new PermissionDeniedException("Attachments can only be added to an open request.");
        }

        var attachment = RequestAttachment.Create(Id, fileName, contentType, sizeBytes, storageKey, actor.UserId, now);
        _attachments.Add(attachment);
        UpdatedAt = now;
        return attachment;
    }

    private void EnsureCanView(Actor actor)
    {
        if (!RequestPolicy.CanView(this, actor))
        {
            throw new PermissionDeniedException("This request belongs to another customer.");
        }
    }
}
